/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./index.html', './src/**/*.{js,jsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'tertiary-fixed': '#e1e2e4',
                'on-tertiary': '#ffffff',
                tertiary: '#121516',
                'inverse-on-surface': '#f0f0f3',
                'secondary-fixed-dim': '#ffb599',
                'surface-container-high': '#e8e8ea',
                primary: '#001430',
                'surface-container-lowest': '#ffffff',
                'on-tertiary-container': '#8e9092',
                'tertiary-container': '#26292b',
                'tertiary-fixed-dim': '#c5c6c8',
                'surface-tint': '#415f8f',
                secondary: '#a63b00',
                'primary-fixed': '#d6e3ff',
                'surface-bright': '#f9f9fc',
                'error-container': '#ffdad6',
                'primary-container': '#002855',
                'on-background': '#1a1c1e',
                'on-error-container': '#93000a',
                'surface-dim': '#dadadc',
                'secondary-container': '#fe5f00',
                'on-surface': '#1a1c1e',
                'outline-variant': '#c4c6d0',
                'on-secondary': '#ffffff',
                'on-tertiary-fixed-variant': '#444749',
                'on-tertiary-fixed': '#191c1e',
                'on-primary-container': '#7490c3',
                'primary-fixed-dim': '#aac7fd',
                'surface-container-highest': '#e2e2e5',
                outline: '#747780',
                'surface-container-low': '#f3f3f6',
                'inverse-primary': '#aac7fd',
                'secondary-fixed': '#ffdbce',
                'on-secondary-container': '#521900',
                background: '#f9f9fc',
                error: '#ba1a1a',
                'on-secondary-fixed-variant': '#7f2b00',
                'surface-variant': '#e2e2e5',
                'on-primary-fixed-variant': '#284775',
                'on-primary': '#ffffff',
                'on-error': '#ffffff',
                'on-primary-fixed': '#001b3d',
                surface: '#f9f9fc',
                'on-surface-variant': '#43474f',
                'inverse-surface': '#2f3133',
                'on-secondary-fixed': '#370e00',
                'surface-container': '#eeeef0',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                'margin-mobile': '16px',
                'margin-desktop': '40px',
                sm: '8px',
                'container-max': '1440px',
                md: '16px',
                lg: '24px',
                unit: '4px',
                gutter: '24px',
                xs: '4px',
                xl: '32px',
            },
            fontFamily: {
                'headline-xl': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'label-lg': ['Inter', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
                'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            },
            maxWidth: {
                'container-max': '1440px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
